import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Velora Design System — exact tokens from design file
        background: "#faf8ff",
        "on-background": "#1a1b21",
        surface: "#faf8ff",
        "surface-dim": "#dad9e1",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3fb",
        "surface-container": "#eeedf5",
        "surface-container-high": "#e8e7ef",
        "surface-container-highest": "#e2e2e9",
        "on-surface": "#1a1b21",
        "on-surface-variant": "#484556",
        "inverse-surface": "#2f3036",
        "inverse-on-surface": "#f1f0f8",
        outline: "#797588",
        "outline-variant": "#c9c4d9",
        "surface-tint": "#5d36ef",
        primary: "#5427e6",
        "on-primary": "#ffffff",
        "primary-container": "#6d4aff",
        "on-primary-container": "#f4eeff",
        "inverse-primary": "#c9bfff",
        secondary: "#585d77",
        "on-secondary": "#ffffff",
        "secondary-container": "#dadefd",
        "on-secondary-container": "#5d617b",
        tertiary: "#00623e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007d51",
        "on-tertiary-container": "#bcffd6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5deff",
        "primary-fixed-dim": "#c9bfff",
        "on-primary-fixed": "#1b0063",
        "on-primary-fixed-variant": "#4500d8",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#c1c5e3",
        "on-secondary-fixed": "#151a31",
        "on-secondary-fixed-variant": "#41455e",
        "surface-variant": "#e2e2e9",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
        // Component-specific radii per design system
        card: "24px",
        button: "16px",
        input: "14px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        xxl: "80px",
      },
      maxWidth: {
        container: "1280px",
      },
      boxShadow: {
        // Tinted, multi-layered soft shadows per design system
        surface: "0 4px 20px rgba(11, 16, 38, 0.04)",
        "surface-md": "0 8px 32px rgba(11, 16, 38, 0.07), 0 2px 8px rgba(11, 16, 38, 0.04)",
        "surface-lg": "0 16px 48px rgba(11, 16, 38, 0.10), 0 4px 16px rgba(11, 16, 38, 0.06)",
        "floating": "0 8px 32px rgba(84, 39, 230, 0.12), 0 2px 8px rgba(11, 16, 38, 0.06)",
        "primary-glow": "0 4px 24px rgba(109, 74, 255, 0.30)",
        "primary-glow-lg": "0 8px 40px rgba(109, 74, 255, 0.35)",
      },
      backgroundImage: {
        "velora-gradient": "linear-gradient(135deg, #6d4aff 0%, #4f46e5 100%)",
        "velora-gradient-hover": "linear-gradient(135deg, #5d3aef 0%, #3f36d5 100%)",
        "velora-glow-radial": "radial-gradient(ellipse at 50% 0%, rgba(109, 74, 255, 0.15) 0%, transparent 70%)",
        "hero-mesh": "radial-gradient(ellipse 80% 60% at 50% -10%, rgba(109, 74, 255, 0.12) 0%, transparent 70%)",
        "card-subtle": "linear-gradient(145deg, #ffffff 0%, #f9f8ff 100%)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "float": "float 6s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "receipt-pop": "receiptPop 0.5s cubic-bezier(0.16, 1, 0.3, 1)",
      },
      keyframes: {
        receiptPop: {
          "0%": { opacity: "0", transform: "scale(0.6)" },
          "60%": { opacity: "1", transform: "scale(1.08)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
