kind = "web"
previewPath = "/"
title = "Velora: Next.js Dev Server"
version = "1.0.0"
id = "Ti9OJlxlcf65D6qijweAZ"

[[services]]
localPort = 3000
name = "Velora: Next.js Dev Server"
paths = ["/"]

[services.env]
PORT = "3000"

[services.development]
run = "pnpm --filter @workspace/velora run dev"
